"""added chat tables

Revision ID: e00715a7b367
Revises: a285aae94b89
Create Date: 2026-01-07 23:27:03.897816+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e00715a7b367"
down_revision: Union[str, Sequence[str], None] = "a285aae94b89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_message",
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("from_user", sa.Boolean(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_message")
    op.drop_table("chat")
    # ### end Alembic commands ###
